#cloud-config
users:
  - name: ubuntu
    shell: /bin/bash
    groups: users
    ssh_import_id: None
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL

  - name: ansible
    shell: /bin/bash
    groups: users
    ssh_import_id: None
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - ansible
  - ansible-lint
  - ca-certificates
  - cloud-init
  - git
  - inxi
  - p7zip-full
  - tree
  - vim
  - wget
package_update: true
package_upgrade: true

runcmd:
  - curl -s https://github.com/pythoninthegrass.keys >> /home/ubuntu/.ssh/authorized_keys
  - git clone https://github.com/pythoninthegrass/apt_lab_tf.git /home/ubuntu/git/apt_lab_tf
  - chown -R ubuntu:ubuntu /home/ubuntu/git/apt_lab_tf
  - touch /var/log/ansible.log && chown ubuntu:ubuntu /var/log/ansible.log

