#cloud-config
users:
  - name: ubuntu
    shell: /bin/bash
    groups: users
    ssh_import_id: None
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    # ssh_authorized_keys:
    #   - ssh-rsa AAAAB3NzaC1yc2E

  - name: ansible
    shell: /bin/bash
    groups: users
    ssh_import_id: None
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL

ansible:
  package_name: ansible-core
  install_method: distro
  pull:
    url: https://github.com/pythoninthegrass/apt_lab_tf.git
    playbook_name: playbook.yml
  run_ansible:
    playbook_dir: master/modules/linux/
    playbook_name: playbook.yml
    tags: qa

runcmd:
  - curl -s https://github.com/pythoninthegrass.keys >> /home/ubuntu/.ssh/authorized_keys
  # - /bin/bash bootstrap.sh

