# code: language=ansible

---
- hosts: localhost
  connection: local
  become: false
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  vars:
    os_environment:
      - key: EDITOR
        value: vim
  pre_tasks:
    - name: Print manual fingerprint instructions
      ansible.builtin.debug:
        msg: |
          # get public ip address
          curl icanhazip.com

          # get private ip address
          ip addr show eth0 | grep -Po 'inet \K[\d.]+'
      tags: qa

    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"
        work_dir: "{{ playbook_dir | dirname }}"
        cacheable: true
      tags: qa

    - name: Top-level directory in project
      ansible.builtin.command: git rev-parse --show-toplevel
      register: tld
      changed_when: false
      tags: qa

    - name: Enable ssh
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true
      tags: qa

    - name: Add deadsnakes ppa
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: true
      become: true
      tags: qa

    - name: Install pip
      become: true
      ansible.builtin.package:
        name: python3-pip
        state: present
      tags: qa

    - name: Cross-platform dependencies
      ansible.builtin.package:
        name:
        - ansible
        - ansible-lint
        - ca-certificates
        - cloud-init
        - git
        - inxi
        - p7zip-full
        - python3.11
        - python3.11-venv
        - tree
        - vim
        - wget
        state: present
      become: true
      tags: qa
  tasks:
    - name: Set /opt permissions
      ansible.builtin.file:
        path: /opt
        mode: '0777'
        state: directory
      become: true
      tags: qa

    - name: Download linuxtools.7z
      ansible.builtin.get_url:
        url: https://github.com/pythoninthegrass/apt_lab_tf_linux/raw/master/linuxtools.7z
        dest: /opt/linuxtools.7z

    - name: Extract linuxtools.7z
      ansible.builtin.unarchive:
        src: /opt/linuxtools.7z
        dest: /opt
        remote_src: true
        extra_opts: -aoa
      tags: qa

    - name: Create tools directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/SilentTrinity
        - /opt/CrackMapExec
      tags: qa

    - name: Move silenttrinity
      ansible.builtin.command: mv /opt/st /opt/SilentTrinity/
      tags: qa

    - name: Move crackmapexec
      ansible.builtin.command: mv /opt/cme* /opt/CrackMapExec/
      tags: qa

    - name: Remove linuxtools.7z
      ansible.builtin.file:
        path: /opt/linuxtools.7z
        state: absent
      tags: qa

    - name: Clone responder
      ansible.builtin.git:
        repo: https://github.com/lgandx/Responder.git
        dest: /opt/Responder
      tags: qa

    - name: Clone impacket
      ansible.builtin.git:
        repo: https://github.com/SecureAuthCorp/impacket.git
        dest: /opt/impacket
      tags: qa

    - name: Setup python virtual environment for impacket
      ansible.builtin.command: python3.11 -m venv /opt/impacket/env
      tags: qa

    - name: Clone helk
      ansible.builtin.git:
        repo: https://github.com/Cyb3rWard0g/HELK.git
        dest: /opt/HELK
      tags: qa

    - name: Run helk docker container
      ansible.builtin.shell: |
        ./helk_install.sh -p hunting -i 10.10.98.20 -b 'helk-kibana-analysis-alert'
      tags: qa
