Param(
   [Parameter(Position=1)]
   [string]$tmppass,

   [Parameter(Position=2)]
   [string]$user

)
$password = ConvertTo-SecureString "$tmppass" -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential ("labs\$user", $password)
New-ADOrganizationalUnit -Server labs.local -Name "UserAccounts" -Credential $Cred
New-ADOrganizationalUnit -Server labs.local -Name "ComputerAccounts" -Credential $Cred
New-ADOrganizationalUnit -Server labs.local -Name "AdminAccounts" -Credential $Cred
redircmp "OU=ComputerAccounts,DC=labs,DC=local"
New-ADUser -UserPrincipalName  Luis.Graves@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Luis" -Surname "Graves" -Enabled 1 -Name "Luis.Graves" -desc "Accounting Controller" -office "Accounting" -title "Controller" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass76918" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Pam.Sparks@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Pam" -Surname "Sparks" -Enabled 1 -Name "Pam.Sparks" -desc "Accounting Accounts Payable" -office "DevLabs Accounting" -title "Accounts Payable" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass30886" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jesus.Robertson@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jesus" -Surname "Robertson" -Enabled 1 -Name "Jesus.Robertson" -desc "Accounting Accounts Receivable" -office "DevLabs Accounting" -title "Accounts Receivable" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass33835" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Nellie.Blair@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Nellie" -Surname "Blair" -Enabled 1 -Name "Nellie.Blair" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass22601" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Carl.Pearson@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Carl" -Surname "Pearson" -Enabled 1 -Name "Carl.Pearson" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass23644" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Geneva.Bryant@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Geneva" -Surname "Bryant" -Enabled 1 -Name "Geneva.Bryant" -desc "WholeSales Wholesale Sales" -office "DevLabs WholeSales" -title "Wholesale Sales" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass59456" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Diana.Henderson@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Diana" -Surname "Henderson" -Enabled 1 -Name "Diana.Henderson" -desc "Transportaion Logistics Manager" -office "DevLabs Transportaion" -title "Logistics Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82796" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Courtney.Mitchell@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Courtney" -Surname "Mitchell" -Enabled 1 -Name "Courtney.Mitchell" -desc "Transportation Logistics Assistant" -office "DevLabs Transportation" -title "Logistics Assistant" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass77145" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gina.Hampton@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gina" -Surname "Hampton" -Enabled 1 -Name "Gina.Hampton" -desc "Bakery Production Director of Bakering" -office "DevLabs Bakery Production" -title "Director of Bakering" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass94578" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Otis.Mullins@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Otis" -Surname "Mullins" -Enabled 1 -Name "Otis.Mullins" -desc "Bakery Production Head Baker" -office "DevLabs Bakery Production" -title "Head Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46747" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gordon.Phillips@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gordon" -Surname "Phillips" -Enabled 1 -Name "Gordon.Phillips" -desc "Bakery Production Head Baker" -office "DevLabs Bakery Production" -title "Head Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass59314" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Olive.Ross@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Olive" -Surname "Ross" -Enabled 1 -Name "Olive.Ross" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass23913" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Roxanne.Greer@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Roxanne" -Surname "Greer" -Enabled 1 -Name "Roxanne.Greer" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass65009" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Willie.Herrera@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Willie" -Surname "Herrera" -Enabled 1 -Name "Willie.Herrera" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass89503" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Randal.Simpson@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Randal" -Surname "Simpson" -Enabled 1 -Name "Randal.Simpson" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass32673" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Bradley.Christensen@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Bradley" -Surname "Christensen" -Enabled 1 -Name "Bradley.Christensen" -desc "Bakery Production Baker" -office "DevLabs Bakery Production" -title "Baker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass67659" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Heather.Butler@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Heather" -Surname "Butler" -Enabled 1 -Name "Heather.Butler" -desc "Bakery Production Purchasing Agent" -office "DevLabs Bakery Production" -title "Purchasing Agent" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass25808" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Elisa.Lawson@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Elisa" -Surname "Lawson" -Enabled 1 -Name "Elisa.Lawson" -desc "Bakery Production Confectionary Specialist" -office "DevLabs Bakery Production" -title "Confectionary Specialist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass93896" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kristi.Silva@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kristi" -Surname "Silva" -Enabled 1 -Name "Kristi.Silva" -desc "Bakery Production Confectionary Specialist" -office "DevLabs Bakery Production" -title "Confectionary Specialist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass66729" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Ed.Barnes@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Ed" -Surname "Barnes" -Enabled 1 -Name "Ed.Barnes" -desc "BusAdmin Office Manager" -office "DevLabs BusAdmin" -title "Office Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass21561" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Angela.Garner@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Angela" -Surname "Garner" -Enabled 1 -Name "Angela.Garner" -desc "Facilities Facilities Manager" -office "DevLabs Facilities" -title "Facilities Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass77813" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Lynda.Bowman@labs.local -Path "OU=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Lynda" -Surname "Bowman" -Enabled 1 -Name "Lynda.Bowman" -desc "IT Systems Support" -office "DevLabs IT" -title "Systems Support" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass28487" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kathleen.Delgado@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kathleen" -Surname "Delgado" -Enabled 1 -Name "Kathleen.Delgado" -desc "IT WebDev Marketer" -office "DevLabs IT" -title "WebDev Marketer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass97825" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Eileen.Moss@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Eileen" -Surname "Moss" -Enabled 1 -Name "Eileen.Moss" -desc "BusAdmin Owner" -office "DevLabs BusAdmin" -title "Owner" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass51776" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  IT.Admin@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "IT" -Surname "Admin" -Enabled 1 -Name "IT.Admin" -desc "IT DEPARTMENT IT SUPERUSER ACCOUNT" -office "DevLabs IT DEPARTMENT" -title "IT SUPERUSER ACCOUNT" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass99999" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Josefina.Robbins@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Josefina" -Surname "Robbins" -Enabled 1 -Name "Josefina.Robbins" -desc "Testing Grounds Of Intervening Epeirogenics Medical Physics Professor" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Medical Physics Professor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass39351" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Toni.Spencer@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Toni" -Surname "Spencer" -Enabled 1 -Name "Toni.Spencer" -desc "Testing Grounds Of Intervening Epeirogenics Sterilization Technician" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Sterilization Technician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass75041" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Becky.Wise@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Becky" -Surname "Wise" -Enabled 1 -Name "Becky.Wise" -desc "Testing Grounds Of Intervening Epeirogenics Honest John Rocket Crew Member" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Honest John Rocket Crew Member" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass55039" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Vicky.Hansen@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Vicky" -Surname "Hansen" -Enabled 1 -Name "Vicky.Hansen" -desc "Testing Grounds Of Intervening Epeirogenics PBX Operator" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "PBX Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass1834" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Juana.Fitzgerald@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Juana" -Surname "Fitzgerald" -Enabled 1 -Name "Juana.Fitzgerald" -desc "Testing Grounds Of Intervening Epeirogenics Field Map Technician" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Field Map Technician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass18832" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Judith.Green@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Judith" -Surname "Green" -Enabled 1 -Name "Judith.Green" -desc "Testing Grounds Of Intervening Epeirogenics Combine Mechanic" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Combine Mechanic" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass91238" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Drew.Simmons@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Drew" -Surname "Simmons" -Enabled 1 -Name "Drew.Simmons" -desc "Testing Grounds Of Intervening Epeirogenics School Bus Driver" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "School Bus Driver" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass53349" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Ernestine.Blake@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Ernestine" -Surname "Blake" -Enabled 1 -Name "Ernestine.Blake" -desc "Testing Grounds Of Intervening Epeirogenics Merchandise Displayer" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "Merchandise Displayer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass12790" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Vickie.Ray@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Vickie" -Surname "Ray" -Enabled 1 -Name "Vickie.Ray" -desc "Testing Grounds Of Intervening Epeirogenics National Association for Stock Car Auto Racing Driver" -office "DevLabs Testing Grounds Of Intervening Epeirogenics" -title "National Association for Stock Car Auto Racing Driver" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass62326" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jerry.Lawrence@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jerry" -Surname "Lawrence" -Enabled 1 -Name "Jerry.Lawrence" -desc "Test Center Of The Analysis Of Florigenics Independent Insurance Adjuster" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Independent Insurance Adjuster" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass55938" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Darlene.Gibbs@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Darlene" -Surname "Gibbs" -Enabled 1 -Name "Darlene.Gibbs" -desc "Test Center Of The Analysis Of Florigenics Electronic Warfare Specialist" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Electronic Warfare Specialist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46644" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jeremy.Willis@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jeremy" -Surname "Willis" -Enabled 1 -Name "Jeremy.Willis" -desc "Test Center Of The Analysis Of Florigenics Administrative Court Justice" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Administrative Court Justice" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass86499" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kathy.Montgomery@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kathy" -Surname "Montgomery" -Enabled 1 -Name "Kathy.Montgomery" -desc "Test Center Of The Analysis Of Florigenics Prescription Clerk" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Prescription Clerk" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass89450" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Veronica.Sparks@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Veronica" -Surname "Sparks" -Enabled 1 -Name "Veronica.Sparks" -desc "Test Center Of The Analysis Of Florigenics Guided Missile Launching System Maintenance Technician" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Guided Missile Launching System Maintenance Technician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass22385" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Bertha.Schultz@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Bertha" -Surname "Schultz" -Enabled 1 -Name "Bertha.Schultz" -desc "Test Center Of The Analysis Of Florigenics Staff Air Defense Officer" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Staff Air Defense Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass90332" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Judy.Bowen@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Judy" -Surname "Bowen" -Enabled 1 -Name "Judy.Bowen" -desc "Test Center Of The Analysis Of Florigenics Film Process Operator" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Film Process Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass76659" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Candace.Martinez@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Candace" -Surname "Martinez" -Enabled 1 -Name "Candace.Martinez" -desc "Test Center Of The Analysis Of Florigenics Aircraft Loadmaster Superintendent" -office "DevLabs Test Center Of The Analysis Of Florigenics" -title "Aircraft Loadmaster Superintendent" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass83152" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Everett.Watkins@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Everett" -Surname "Watkins" -Enabled 1 -Name "Everett.Watkins" -desc "Defense Lab Of Obscure Transgenics Lay Health Advocate" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Lay Health Advocate" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass16102" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Mandy.Rhodes@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Mandy" -Surname "Rhodes" -Enabled 1 -Name "Mandy.Rhodes" -desc "Test Center Of Declined Ergogenics Geophysical Manager" -office "DevLabs Test Center Of Declined Ergogenics" -title "Geophysical Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass31055" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gail.Kennedy@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gail" -Surname "Kennedy" -Enabled 1 -Name "Gail.Kennedy" -desc "Defense Lab Of Obscure Transgenics Ship's Electronic Warfare Officer" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Ship's Electronic Warfare Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass60705" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Elmer.Wagner@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Elmer" -Surname "Wagner" -Enabled 1 -Name "Elmer.Wagner" -desc "Test Center Of Declined Ergogenics MIS Director" -office "DevLabs Test Center Of Declined Ergogenics" -title "MIS Director" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass7611" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Angela.Hampton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Angela" -Surname "Hampton" -Enabled 1 -Name "Angela.Hampton" -desc "Defense Lab Of Obscure Transgenics Peer Health Promoter" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Peer Health Promoter" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass60044" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Claire.Munoz@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Claire" -Surname "Munoz" -Enabled 1 -Name "Claire.Munoz" -desc "Test Center Of Declined Ergogenics Secondary School Principal" -office "DevLabs Test Center Of Declined Ergogenics" -title "Secondary School Principal" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass11608" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Joanna.Patton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Joanna" -Surname "Patton" -Enabled 1 -Name "Joanna.Patton" -desc "Defense Lab Of Obscure Transgenics Banquet Manager" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Banquet Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass59451" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Elaine.Carson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Elaine" -Surname "Carson" -Enabled 1 -Name "Elaine.Carson" -desc "Test Center Of Declined Ergogenics Service Forester" -office "DevLabs Test Center Of Declined Ergogenics" -title "Service Forester" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass30285" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Shelia.Osborne@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Shelia" -Surname "Osborne" -Enabled 1 -Name "Shelia.Osborne" -desc "Defense Lab Of Obscure Transgenics Computer Security Specialist" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Computer Security Specialist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46566" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Alberto.Patterson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Alberto" -Surname "Patterson" -Enabled 1 -Name "Alberto.Patterson" -desc "Test Center Of Declined Ergogenics Computer Systems Security Analyst" -office "DevLabs Test Center Of Declined Ergogenics" -title "Computer Systems Security Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass31258" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Bonnie.Barber@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Bonnie" -Surname "Barber" -Enabled 1 -Name "Bonnie.Barber" -desc "Defense Lab Of Obscure Transgenics Information Security Analyst" -office "DevLabs Defense Lab Of Obscure Transgenics" -title "Information Security Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass8383" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Christian.Frazier@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Christian" -Surname "Frazier" -Enabled 1 -Name "Christian.Frazier" -desc "Test Center Of Declined Ergogenics Information Systems Security Analyst" -office "DevLabs Test Center Of Declined Ergogenics" -title "Information Systems Security Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass85995" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Cheryl.Ford@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Cheryl" -Surname "Ford" -Enabled 1 -Name "Cheryl.Ford" -desc "Test Center Of The Deterioration Of Palynology Internet Security Specialist" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Internet Security Specialist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass42850" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Leslie.Francis@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Leslie" -Surname "Francis" -Enabled 1 -Name "Leslie.Francis" -desc "Test Center Of The Deterioration Of Palynology Network Security Analyst" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Network Security Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass79876" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Dwight.Burns@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Dwight" -Surname "Burns" -Enabled 1 -Name "Dwight.Burns" -desc "Test Center Of The Deterioration Of Palynology Applications Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Applications Programmer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46592" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jill.Roberts@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jill" -Surname "Roberts" -Enabled 1 -Name "Jill.Roberts" -desc "Test Center Of The Deterioration Of Palynology Computer Language Coder" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Computer Language Coder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass57759" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Tamara.Armstrong@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Tamara" -Surname "Armstrong" -Enabled 1 -Name "Tamara.Armstrong" -desc "Test Center Of The Deterioration Of Palynology Computer Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Computer Programmer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass32165" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Lionel.Vaughn@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Lionel" -Surname "Vaughn" -Enabled 1 -Name "Lionel.Vaughn" -desc "Test Center Of The Deterioration Of Palynology Junior Software Developer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Junior Software Developer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass65184" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Carmen.Chambers@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Carmen" -Surname "Chambers" -Enabled 1 -Name "Carmen.Chambers" -desc "Test Center Of The Deterioration Of Palynology Mainframe Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Mainframe Programmer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass31637" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Taylor.Gill@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Taylor" -Surname "Gill" -Enabled 1 -Name "Taylor.Gill" -desc "Test Center Of The Deterioration Of Palynology Systems Programmer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Systems Programmer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass39026" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Cora.Bowman@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Cora" -Surname "Bowman" -Enabled 1 -Name "Cora.Bowman" -desc "Test Center Of The Deterioration Of Palynology Application Integration Engineer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Application Integration Engineer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass87180" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Virginia.Adkins@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Virginia" -Surname "Adkins" -Enabled 1 -Name "Virginia.Adkins" -desc "Test Center Of The Deterioration Of Palynology Applications Developer" -office "DevLabs Test Center Of The Deterioration Of Palynology" -title "Applications Developer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass56388" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jody.Haynes@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jody" -Surname "Haynes" -Enabled 1 -Name "Jody.Haynes" -desc "Research Lab Of Mutating Garbology Computer Applications Developer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Computer Applications Developer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass59005" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Corey.Quinn@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Corey" -Surname "Quinn" -Enabled 1 -Name "Corey.Quinn" -desc "Research Lab Of Mutating Garbology Computer Applications Engineer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Computer Applications Engineer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass85030" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Nancy.Yates@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Nancy" -Surname "Yates" -Enabled 1 -Name "Nancy.Yates" -desc "Research Lab Of Mutating Garbology Database Developer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Database Developer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass43517" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Eleanor.Olson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Eleanor" -Surname "Olson" -Enabled 1 -Name "Eleanor.Olson" -desc "Research Lab Of Mutating Garbology Software Applications Architect" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Architect" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass74648" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Shari.Hunt@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Shari" -Surname "Hunt" -Enabled 1 -Name "Shari.Hunt" -desc "Research Lab Of Mutating Garbology Software Applications Designer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Designer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass63423" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Willie.Gonzales@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Willie" -Surname "Gonzales" -Enabled 1 -Name "Willie.Gonzales" -desc "Research Lab Of Mutating Garbology Software Applications Engineer" -office "DevLabs Research Lab Of Mutating Garbology" -title "Software Applications Engineer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass57169" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Rickey.Campbell@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Rickey" -Surname "Campbell" -Enabled 1 -Name "Rickey.Campbell" -desc "Research Lab Of Mutating Garbology Actuarial Associate" -office "DevLabs Research Lab Of Mutating Garbology" -title "Actuarial Associate" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass91838" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Pablo.Goodman@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Pablo" -Surname "Goodman" -Enabled 1 -Name "Pablo.Goodman" -desc "Research Lab Of Mutating Garbology Actuarial Mathematician" -office "DevLabs Research Lab Of Mutating Garbology" -title "Actuarial Mathematician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass71031" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Maureen.Rios@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Maureen" -Surname "Rios" -Enabled 1 -Name "Maureen.Rios" -desc "Defense Lab Of The Rectification Of Dysgenics Health Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Health Actuary" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass5877" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jim.Bailey@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jim" -Surname "Bailey" -Enabled 1 -Name "Jim.Bailey" -desc "Defense Lab Of The Rectification Of Dysgenics Insurance Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Insurance Actuary" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass13637" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Debbie.Harrison@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Debbie" -Surname "Harrison" -Enabled 1 -Name "Debbie.Harrison" -desc "Defense Lab Of The Rectification Of Dysgenics Pricing Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Pricing Actuary" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass34971" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Timmy.Richardson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Timmy" -Surname "Richardson" -Enabled 1 -Name "Timmy.Richardson" -desc "Defense Lab Of The Rectification Of Dysgenics Product Development Actuary" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Product Development Actuary" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46037" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Samantha.Ryan@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Samantha" -Surname "Ryan" -Enabled 1 -Name "Samantha.Ryan" -desc "Defense Lab Of The Rectification Of Dysgenics Operations Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Operations Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass5033" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Roderick.Stone@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Roderick" -Surname "Stone" -Enabled 1 -Name "Roderick.Stone" -desc "Defense Lab Of The Rectification Of Dysgenics Operations Research Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Operations Research Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass1984" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jackie.Hall@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jackie" -Surname "Hall" -Enabled 1 -Name "Jackie.Hall" -desc "Defense Lab Of The Rectification Of Dysgenics Procedure Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Procedure Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass62950" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Sylvia.Mcgee@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Sylvia" -Surname "Mcgee" -Enabled 1 -Name "Sylvia.Mcgee" -desc "Defense Lab Of The Rectification Of Dysgenics Process Analyst" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Process Analyst" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass81222" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Bernice.Lawson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Bernice" -Surname "Lawson" -Enabled 1 -Name "Bernice.Lawson" -desc "Defense Lab Of The Rectification Of Dysgenics Animal Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Animal Breeder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass54618" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kyle.Owen@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kyle" -Surname "Owen" -Enabled 1 -Name "Kyle.Owen" -desc "Defense Lab Of The Rectification Of Dysgenics Cat Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Cat Breeder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass64815" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Orlando.Bennett@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Orlando" -Surname "Bennett" -Enabled 1 -Name "Orlando.Bennett" -desc "Defense Lab Of The Rectification Of Dysgenics Dairy Husbandry Worker" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Dairy Husbandry Worker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass83275" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Cindy.Vargas@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Cindy" -Surname "Vargas" -Enabled 1 -Name "Cindy.Vargas" -desc "Defense Lab Of The Rectification Of Dysgenics Dog Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Dog Breeder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass73142" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Geneva.Murphy@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Geneva" -Surname "Murphy" -Enabled 1 -Name "Geneva.Murphy" -desc "Defense Lab Of The Rectification Of Dysgenics Equine Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Equine Breeder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass79401" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Paula.Warner@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Paula" -Surname "Warner" -Enabled 1 -Name "Paula.Warner" -desc "Defense Lab Of The Rectification Of Dysgenics Horse Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Horse Breeder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass78584" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Felix.Ballard@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Felix" -Surname "Ballard" -Enabled 1 -Name "Felix.Ballard" -desc "Defense Lab Of The Rectification Of Dysgenics Livestock Breeder" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Livestock Breeder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass6354" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Phyllis.Rivera@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Phyllis" -Surname "Rivera" -Enabled 1 -Name "Phyllis.Rivera" -desc "Defense Lab Of The Rectification Of Dysgenics Poultry Inseminator" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Poultry Inseminator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82528" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Harriet.Moss@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Harriet" -Surname "Moss" -Enabled 1 -Name "Harriet.Moss" -desc "Defense Lab Of The Rectification Of Dysgenics Stallion Manager" -office "DevLabs Defense Lab Of The Rectification Of Dysgenics" -title "Stallion Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass21525" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Lucille.Tucker@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Lucille" -Surname "Tucker" -Enabled 1 -Name "Lucille.Tucker" -desc "Plutocratic Republic of Prefectures Rug Designer" -office "DevLabs Plutocratic Republic of Prefectures" -title "Rug Designer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass7198" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Oscar.Sherman@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Oscar" -Surname "Sherman" -Enabled 1 -Name "Oscar.Sherman" -desc "Plutocratic Republic of Prefectures Special Education Preschool Teacher" -office "DevLabs Plutocratic Republic of Prefectures" -title "Special Education Preschool Teacher" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass26745" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Priscilla.Bryant@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Priscilla" -Surname "Bryant" -Enabled 1 -Name "Priscilla.Bryant" -desc "Plutocratic Republic of Prefectures Radio Television Technical Director" -office "DevLabs Plutocratic Republic of Prefectures" -title "Radio Television Technical Director" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass37534" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gwendolyn.Berry@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gwendolyn" -Surname "Berry" -Enabled 1 -Name "Gwendolyn.Berry" -desc "Plutocratic Republic of Prefectures Rail Signal Mechanic" -office "DevLabs Plutocratic Republic of Prefectures" -title "Rail Signal Mechanic" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass16263" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Cynthia.Mcdonald@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Cynthia" -Surname "Mcdonald" -Enabled 1 -Name "Cynthia.Mcdonald" -desc "Plutocratic Republic of Prefectures Funeral Arrangement Director" -office "DevLabs Plutocratic Republic of Prefectures" -title "Funeral Arrangement Director" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass67127" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Ignacio.Long@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Ignacio" -Surname "Long" -Enabled 1 -Name "Ignacio.Long" -desc "Plutocratic Republic of Prefectures Tool Room Supervisor" -office "DevLabs Plutocratic Republic of Prefectures" -title "Tool Room Supervisor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass59735" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Patsy.Medina@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Patsy" -Surname "Medina" -Enabled 1 -Name "Patsy.Medina" -desc "Plutocratic Republic of Prefectures Non-Acoustic Operator" -office "DevLabs Plutocratic Republic of Prefectures" -title "Non-Acoustic Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass58883" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Spencer.Watts@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Spencer" -Surname "Watts" -Enabled 1 -Name "Spencer.Watts" -desc "Plutocratic Republic of Prefectures Foundry Molder" -office "DevLabs Plutocratic Republic of Prefectures" -title "Foundry Molder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass11676" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Stuart.Poole@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Stuart" -Surname "Poole" -Enabled 1 -Name "Stuart.Poole" -desc "Plutocratic Republic of Prefectures Coal Tram Driver" -office "DevLabs Plutocratic Republic of Prefectures" -title "Coal Tram Driver" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass68767" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Dana.Horton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Dana" -Surname "Horton" -Enabled 1 -Name "Dana.Horton" -desc "Plutocratic Republic of Prefectures Cage Cashier" -office "DevLabs Plutocratic Republic of Prefectures" -title "Cage Cashier" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass89692" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Luz.Boone@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Luz" -Surname "Boone" -Enabled 1 -Name "Luz.Boone" -desc "Plutocratic Republic of Prefectures Golf Course Laborer" -office "DevLabs Plutocratic Republic of Prefectures" -title "Golf Course Laborer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass6850" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Diane.Sims@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Diane" -Surname "Sims" -Enabled 1 -Name "Diane.Sims" -desc "Plutocratic Republic of Prefectures Aegis Console Operator Track 3" -office "DevLabs Plutocratic Republic of Prefectures" -title "Aegis Console Operator Track 3" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass10158" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Joanne.Stewart@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Joanne" -Surname "Stewart" -Enabled 1 -Name "Joanne.Stewart" -desc "Plutocratic Republic of Prefectures Dairy Husbandry Worker" -office "DevLabs Plutocratic Republic of Prefectures" -title "Dairy Husbandry Worker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass19993" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Wallace.West@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Wallace" -Surname "West" -Enabled 1 -Name "Wallace.West" -desc "Plutocratic Republic of Prefectures Airborne Mission Systems Superintendent" -office "DevLabs Plutocratic Republic of Prefectures" -title "Airborne Mission Systems Superintendent" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass61788" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Nellie.Higgins@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Nellie" -Surname "Higgins" -Enabled 1 -Name "Nellie.Higgins" -desc "Plutocratic Republic of Prefectures An/Sqq-32(V)3 Minehunting Sonar Set Operator (Mss)" -office "DevLabs Plutocratic Republic of Prefectures" -title "An/Sqq-32(V)3 Minehunting Sonar Set Operator (Mss)" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass85310" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gabriel.Roberson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gabriel" -Surname "Roberson" -Enabled 1 -Name "Gabriel.Roberson" -desc "Plutocratic Republic of Prefectures Certified Mortician" -office "DevLabs Plutocratic Republic of Prefectures" -title "Certified Mortician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass61561" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Roberto.Lyons@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Roberto" -Surname "Lyons" -Enabled 1 -Name "Roberto.Lyons" -desc "The Light Academy National Association for Stock Car Auto Racing Driver" -office "DevLabs The Light Academy" -title "National Association for Stock Car Auto Racing Driver" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass52164" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Beverly.Lucas@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Beverly" -Surname "Lucas" -Enabled 1 -Name "Beverly.Lucas" -desc "The Light Academy Souvenir Street Vendor" -office "DevLabs The Light Academy" -title "Souvenir Street Vendor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass1874" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Dorothy.Pearson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Dorothy" -Surname "Pearson" -Enabled 1 -Name "Dorothy.Pearson" -desc "The Light Academy Conductor" -office "DevLabs The Light Academy" -title "Conductor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass76416" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Glen.Shaw@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Glen" -Surname "Shaw" -Enabled 1 -Name "Glen.Shaw" -desc "The Light Academy Meter Maid" -office "DevLabs The Light Academy" -title "Meter Maid" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass17321" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Ginger.Wilkins@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Ginger" -Surname "Wilkins" -Enabled 1 -Name "Ginger.Wilkins" -desc "The Light Academy Victorian Literature Professor" -office "DevLabs The Light Academy" -title "Victorian Literature Professor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass56275" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Leona.Wallace@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Leona" -Surname "Wallace" -Enabled 1 -Name "Leona.Wallace" -desc "The Light Academy Deck Cadet" -office "DevLabs The Light Academy" -title "Deck Cadet" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass80651" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Chester.Dean@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Chester" -Surname "Dean" -Enabled 1 -Name "Chester.Dean" -desc "The Light Academy Objects Conservator" -office "DevLabs The Light Academy" -title "Objects Conservator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass21023" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Rosalie.Torres@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Rosalie" -Surname "Torres" -Enabled 1 -Name "Rosalie.Torres" -desc "The Light Academy Naval Aircrewman Avionics" -office "DevLabs The Light Academy" -title "Naval Aircrewman Avionics" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass62974" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gerardo.Ross@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gerardo" -Surname "Ross" -Enabled 1 -Name "Gerardo.Ross" -desc "The Light Academy Real Estate Loan Officer" -office "DevLabs The Light Academy" -title "Real Estate Loan Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass97522" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Charlene.Shelton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Charlene" -Surname "Shelton" -Enabled 1 -Name "Charlene.Shelton" -desc "The Light Academy Pipe Fitter" -office "DevLabs The Light Academy" -title "Pipe Fitter" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass47743" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Joyce.Jefferson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Joyce" -Surname "Jefferson" -Enabled 1 -Name "Joyce.Jefferson" -desc "Integrated Gyrohands Television Repairer" -office "DevLabs Integrated Gyrohands" -title "Television Repairer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass4557" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Damon.Rodriguez@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Damon" -Surname "Rodriguez" -Enabled 1 -Name "Damon.Rodriguez" -desc "Protonic Distortion Wardrobe Custodian" -office "DevLabs Protonic Distortion" -title "Wardrobe Custodian" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82446" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Oliver.Barton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Oliver" -Surname "Barton" -Enabled 1 -Name "Oliver.Barton" -desc "Office of Programming Troubleshooting and Application Security Highway Inspector" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Highway Inspector" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass10237" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Janis.Sutton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Janis" -Surname "Sutton" -Enabled 1 -Name "Janis.Sutton" -desc "Office of Programming Troubleshooting and Application Security Mortgage Closing Clerk" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Mortgage Closing Clerk" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass48899" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Paul.Moran@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Paul" -Surname "Moran" -Enabled 1 -Name "Paul.Moran" -desc "Office of Programming Troubleshooting and Application Security Journalism Professor" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Journalism Professor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass55810" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Enrique.Gomez@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Enrique" -Surname "Gomez" -Enabled 1 -Name "Enrique.Gomez" -desc "Office of Programming Troubleshooting and Application Security Vacuum Cleaner Repair Person" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Vacuum Cleaner Repair Person" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass71668" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Walter.Cannon@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Walter" -Surname "Cannon" -Enabled 1 -Name "Walter.Cannon" -desc "Office of Programming Troubleshooting and Application Security Paddock Judge" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Paddock Judge" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass61960" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Antonio.Garza@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Antonio" -Surname "Garza" -Enabled 1 -Name "Antonio.Garza" -desc "Office of Programming Troubleshooting and Application Security Aviation Ordnance Officer" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Aviation Ordnance Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass5241" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kent.Sullivan@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kent" -Surname "Sullivan" -Enabled 1 -Name "Kent.Sullivan" -desc "Office of Programming Troubleshooting and Application Security Career Technical Counselor" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Career Technical Counselor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass17022" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Sonia.Griffith@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Sonia" -Surname "Griffith" -Enabled 1 -Name "Sonia.Griffith" -desc "Office of Programming Troubleshooting and Application Security Maxillofacial Prosthodontist" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Maxillofacial Prosthodontist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass11371" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jean.Ross@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jean" -Surname "Ross" -Enabled 1 -Name "Jean.Ross" -desc "Office of Programming Troubleshooting and Application Security Stoker Installer" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Stoker Installer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass15372" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kerry.Byrd@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kerry" -Surname "Byrd" -Enabled 1 -Name "Kerry.Byrd" -desc "Office of Programming Troubleshooting and Application Security Billiard Player" -office "DevLabs Office of Programming Troubleshooting and Application Security" -title "Billiard Player" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass73384" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Wallace.Watson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Wallace" -Surname "Watson" -Enabled 1 -Name "Wallace.Watson" -desc "PC Troubleshooting Branch Foreign Exchange Position Clerk" -office "DevLabs PC Troubleshooting Branch" -title "Foreign Exchange Position Clerk" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass37450" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jill.Campbell@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jill" -Surname "Campbell" -Enabled 1 -Name "Jill.Campbell" -desc "PC Troubleshooting Branch Estate Conservator" -office "DevLabs PC Troubleshooting Branch" -title "Estate Conservator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass25598" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Regina.Neal@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Regina" -Surname "Neal" -Enabled 1 -Name "Regina.Neal" -desc "PC Troubleshooting Branch Mortgage Accounting Clerk" -office "DevLabs PC Troubleshooting Branch" -title "Mortgage Accounting Clerk" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass38541" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Vanessa.Floyd@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Vanessa" -Surname "Floyd" -Enabled 1 -Name "Vanessa.Floyd" -desc "PC Troubleshooting Branch Economic Geographer" -office "DevLabs PC Troubleshooting Branch" -title "Economic Geographer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82092" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Essie.Mclaughlin@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Essie" -Surname "Mclaughlin" -Enabled 1 -Name "Essie.Mclaughlin" -desc "PC Troubleshooting Branch Head Greenskeeper" -office "DevLabs PC Troubleshooting Branch" -title "Head Greenskeeper" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass30530" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Dana.Johnson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Dana" -Surname "Johnson" -Enabled 1 -Name "Dana.Johnson" -desc "PC Troubleshooting Branch Public Affairs Officer" -office "DevLabs PC Troubleshooting Branch" -title "Public Affairs Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass41884" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Mona.Ballard@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Mona" -Surname "Ballard" -Enabled 1 -Name "Mona.Ballard" -desc "PC Troubleshooting Branch Manufacturing Engineering Professor" -office "DevLabs PC Troubleshooting Branch" -title "Manufacturing Engineering Professor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82899" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Santiago.Parks@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Santiago" -Surname "Parks" -Enabled 1 -Name "Santiago.Parks" -desc "PC Troubleshooting Branch Drug Abuse Counselor" -office "DevLabs PC Troubleshooting Branch" -title "Drug Abuse Counselor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass67974" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Cristina.Page@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Cristina" -Surname "Page" -Enabled 1 -Name "Cristina.Page" -desc "PC Troubleshooting Branch Airborne Operations Manager" -office "DevLabs PC Troubleshooting Branch" -title "Airborne Operations Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass4564" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Harvey.Brady@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Harvey" -Surname "Brady" -Enabled 1 -Name "Harvey.Brady" -desc "PC Troubleshooting Branch Florist" -office "DevLabs PC Troubleshooting Branch" -title "Florist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass98763" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Grace.Turner@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Grace" -Surname "Turner" -Enabled 1 -Name "Grace.Turner" -desc "Agency of Portable PC Implementation Stage Electrician" -office "DevLabs Agency of Portable PC Implementation" -title "Stage Electrician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass79900" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Katie.Maxwell@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Katie" -Surname "Maxwell" -Enabled 1 -Name "Katie.Maxwell" -desc "Agency of Portable PC Implementation Bilingual Kindergarten Teacher" -office "DevLabs Agency of Portable PC Implementation" -title "Bilingual Kindergarten Teacher" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass23686" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Don.Potter@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Don" -Surname "Potter" -Enabled 1 -Name "Don.Potter" -desc "Agency of Portable PC Implementation Construction Ironworker Helper" -office "DevLabs Agency of Portable PC Implementation" -title "Construction Ironworker Helper" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82814" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Loren.Elliott@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Loren" -Surname "Elliott" -Enabled 1 -Name "Loren.Elliott" -desc "Agency of Portable PC Implementation Visual Merchandiser" -office "DevLabs Agency of Portable PC Implementation" -title "Visual Merchandiser" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass11447" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Marcia.Fitzgerald@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Marcia" -Surname "Fitzgerald" -Enabled 1 -Name "Marcia.Fitzgerald" -desc "Agency of Portable PC Implementation Telesales Supervisor" -office "DevLabs Agency of Portable PC Implementation" -title "Telesales Supervisor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass88006" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Sylvia.Sutton@labs.local -Path "ou=AdminAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Sylvia" -Surname "Sutton" -Enabled 1 -Name "Sylvia.Sutton" -desc "Agency of Portable PC Implementation Fire Control Officer" -office "DevLabs Agency of Portable PC Implementation" -title "Fire Control Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass11813" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Rosemary.Peterson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Rosemary" -Surname "Peterson" -Enabled 1 -Name "Rosemary.Peterson" -desc "Code Security and PC Technology Team Cement Truck Driver" -office "DevLabs Code Security and PC Technology Team" -title "Cement Truck Driver" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass44039" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Anthony.Caldwell@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Anthony" -Surname "Caldwell" -Enabled 1 -Name "Anthony.Caldwell" -desc "Code Security and PC Technology Team Window Cleaner" -office "DevLabs Code Security and PC Technology Team" -title "Window Cleaner" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass78369" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Brooke.Webster@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Brooke" -Surname "Webster" -Enabled 1 -Name "Brooke.Webster" -desc "Code Security and PC Technology Team Licensed Clinical Mental Health Counselor" -office "DevLabs Code Security and PC Technology Team" -title "Licensed Clinical Mental Health Counselor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass22968" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Penny.Gregory@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Penny" -Surname "Gregory" -Enabled 1 -Name "Penny.Gregory" -desc "Code Security and PC Technology Team Store Gift Wrap Associate" -office "DevLabs Code Security and PC Technology Team" -title "Store Gift Wrap Associate" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass29522" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Dominic.Mendoza@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Dominic" -Surname "Mendoza" -Enabled 1 -Name "Dominic.Mendoza" -desc "Code Security and PC Technology Team Traveling Missionary" -office "DevLabs Code Security and PC Technology Team" -title "Traveling Missionary" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass45551" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Ethel.Bishop@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Ethel" -Surname "Bishop" -Enabled 1 -Name "Ethel.Bishop" -desc "Code Security and PC Technology Team Tax Compliance Representative" -office "DevLabs Code Security and PC Technology Team" -title "Tax Compliance Representative" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass14715" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kelvin.Ortiz@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kelvin" -Surname "Ortiz" -Enabled 1 -Name "Kelvin.Ortiz" -desc "Code Security and PC Technology Team Hotel Baggage Handler" -office "DevLabs Code Security and PC Technology Team" -title "Hotel Baggage Handler" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass73993" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Caleb.Kennedy@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Caleb" -Surname "Kennedy" -Enabled 1 -Name "Caleb.Kennedy" -desc "Code Security and PC Technology Team Registered Medical Transcriptionist" -office "DevLabs Code Security and PC Technology Team" -title "Registered Medical Transcriptionist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass76530" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Randal.Parsons@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Randal" -Surname "Parsons" -Enabled 1 -Name "Randal.Parsons" -desc "Code Security and PC Technology Team Pugilist" -office "DevLabs Code Security and PC Technology Team" -title "Pugilist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass11028" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Seth.Harper@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Seth" -Surname "Harper" -Enabled 1 -Name "Seth.Harper" -desc "Code Security and PC Technology Team Wholesale Ultrasonic Equipment Salesperson" -office "DevLabs Code Security and PC Technology Team" -title "Wholesale Ultrasonic Equipment Salesperson" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass74210" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Debra.Thornton@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Debra" -Surname "Thornton" -Enabled 1 -Name "Debra.Thornton" -desc "Illuminated Technocracy Sports Complex Attendant" -office "DevLabs Illuminated Technocracy" -title "Sports Complex Attendant" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass84977" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jessie.Schmidt@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jessie" -Surname "Schmidt" -Enabled 1 -Name "Jessie.Schmidt" -desc "Illuminated Technocracy Boiler Operator" -office "DevLabs Illuminated Technocracy" -title "Boiler Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass44945" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Antoinette.Morrison@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Antoinette" -Surname "Morrison" -Enabled 1 -Name "Antoinette.Morrison" -desc "Illuminated Technocracy Booking Manager" -office "DevLabs Illuminated Technocracy" -title "Booking Manager" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass96146" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Mark.Mccormick@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Mark" -Surname "Mccormick" -Enabled 1 -Name "Mark.Mccormick" -desc "Illuminated Technocracy Registered Medical Transcriptionist" -office "DevLabs Illuminated Technocracy" -title "Registered Medical Transcriptionist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass43688" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jeanette.Wise@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jeanette" -Surname "Wise" -Enabled 1 -Name "Jeanette.Wise" -desc "Illuminated Technocracy Tape Editor" -office "DevLabs Illuminated Technocracy" -title "Tape Editor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass56301" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Elena.Hernandez@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Elena" -Surname "Hernandez" -Enabled 1 -Name "Elena.Hernandez" -desc "Illuminated Technocracy Cotton Ginner" -office "DevLabs Illuminated Technocracy" -title "Cotton Ginner" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass95861" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Bob.King@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Bob" -Surname "King" -Enabled 1 -Name "Bob.King" -desc "Radioactive Team Glacier Music Adapter" -office "DevLabs Radioactive Team Glacier" -title "Music Adapter" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46339" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Vera.Daniels@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Vera" -Surname "Daniels" -Enabled 1 -Name "Vera.Daniels" -desc "Radioactive Team Glacier Poultry Inseminator" -office "DevLabs Radioactive Team Glacier" -title "Poultry Inseminator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass78347" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Colleen.Blair@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Colleen" -Surname "Blair" -Enabled 1 -Name "Colleen.Blair" -desc "Radioactive Team Glacier DTR" -office "DevLabs Radioactive Team Glacier" -title "DTR" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass19252" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Arlene.Poole@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Arlene" -Surname "Poole" -Enabled 1 -Name "Arlene.Poole" -desc "Radioactive Team Glacier Songwriter" -office "DevLabs Radioactive Team Glacier" -title "Songwriter" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass78687" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Stella.Palmer@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Stella" -Surname "Palmer" -Enabled 1 -Name "Stella.Palmer" -desc "Radioactive Team Glacier Bicycle Racer" -office "DevLabs Radioactive Team Glacier" -title "Bicycle Racer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass77917" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Phil.Hogan@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Phil" -Surname "Hogan" -Enabled 1 -Name "Phil.Hogan" -desc "Radioactive Team Glacier Certified Nurse Midwife (CNM)" -office "DevLabs Radioactive Team Glacier" -title "Certified Nurse Midwife (CNM)" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass69445" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Angelo.Richards@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Angelo" -Surname "Richards" -Enabled 1 -Name "Angelo.Richards" -desc "Radioactive Team Glacier Field Enumerator" -office "DevLabs Radioactive Team Glacier" -title "Field Enumerator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass97334" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jasmine.Lawson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jasmine" -Surname "Lawson" -Enabled 1 -Name "Jasmine.Lawson" -desc "Radioactive Team Glacier Industrial Photographer" -office "DevLabs Radioactive Team Glacier" -title "Industrial Photographer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass30977" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Julio.Davis@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Julio" -Surname "Davis" -Enabled 1 -Name "Julio.Davis" -desc "Radioactive Team Glacier Early Childhood Special Education Teacher" -office "DevLabs Radioactive Team Glacier" -title "Early Childhood Special Education Teacher" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass46270" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Monique.Price@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Monique" -Surname "Price" -Enabled 1 -Name "Monique.Price" -desc "Radioactive Team Glacier Telephone Interviewer" -office "DevLabs Radioactive Team Glacier" -title "Telephone Interviewer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass788" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gerardo.Lindsey@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gerardo" -Surname "Lindsey" -Enabled 1 -Name "Gerardo.Lindsey" -desc "Radioactive Team Glacier Adult Nurse Practitioner" -office "DevLabs Radioactive Team Glacier" -title "Adult Nurse Practitioner" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass96589" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Terrence.Chapman@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Terrence" -Surname "Chapman" -Enabled 1 -Name "Terrence.Chapman" -desc "Radioactive Team Glacier Airset Caster" -office "DevLabs Radioactive Team Glacier" -title "Airset Caster" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass68831" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Horace.Alvarado@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Horace" -Surname "Alvarado" -Enabled 1 -Name "Horace.Alvarado" -desc "Radioactive Team Glacier Counterintelligence" -office "DevLabs Radioactive Team Glacier" -title "Counterintelligence/Human Intelligence Senior Sergeant" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass13042" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jeannie.Jacobs@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jeannie" -Surname "Jacobs" -Enabled 1 -Name "Jeannie.Jacobs" -desc "Radioactive Team Glacier Ship Purser" -office "DevLabs Radioactive Team Glacier" -title "Ship Purser" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass55527" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Irvin.May@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Irvin" -Surname "May" -Enabled 1 -Name "Irvin.May" -desc "Radioactive Team Glacier Poker Room Supervisor" -office "DevLabs Radioactive Team Glacier" -title "Poker Room Supervisor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass60479" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Rafael.Colon@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Rafael" -Surname "Colon" -Enabled 1 -Name "Rafael.Colon" -desc "Radioactive Team Glacier Licensed Massage Therapist" -office "DevLabs Radioactive Team Glacier" -title "Licensed Massage Therapist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass40962" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gertrude.Kim@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gertrude" -Surname "Kim" -Enabled 1 -Name "Gertrude.Kim" -desc "Titanium Task Force Magnetic Fire Control Officer" -office "DevLabs Titanium Task Force Magnetic" -title "Fire Control Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass87915" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Angela.Knight@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Angela" -Surname "Knight" -Enabled 1 -Name "Angela.Knight" -desc "Titanium Task Force Magnetic Motor Rewinder" -office "DevLabs Titanium Task Force Magnetic" -title "Motor Rewinder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass80578" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Janie.Goodwin@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Janie" -Surname "Goodwin" -Enabled 1 -Name "Janie.Goodwin" -desc "Titanium Task Force Magnetic Airplane Refueler" -office "DevLabs Titanium Task Force Magnetic" -title "Airplane Refueler" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass83974" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Stephen.Mckinney@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Stephen" -Surname "Mckinney" -Enabled 1 -Name "Stephen.Mckinney" -desc "Titanium Task Force Magnetic Marine Architect" -office "DevLabs Titanium Task Force Magnetic" -title "Marine Architect" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass73138" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Eleanor.Abbott@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Eleanor" -Surname "Abbott" -Enabled 1 -Name "Eleanor.Abbott" -desc "Titanium Task Force Magnetic Harvest Crew Supervisor" -office "DevLabs Titanium Task Force Magnetic" -title "Harvest Crew Supervisor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass68" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Perry.Newman@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Perry" -Surname "Newman" -Enabled 1 -Name "Perry.Newman" -desc "Titanium Task Force Magnetic Compressor Station Operator" -office "DevLabs Titanium Task Force Magnetic" -title "Compressor Station Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass2396" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Dan.Richardson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Dan" -Surname "Richardson" -Enabled 1 -Name "Dan.Richardson" -desc "Titanium Task Force Magnetic Street Sweeper Operator" -office "DevLabs Titanium Task Force Magnetic" -title "Street Sweeper Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass6205" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Kim.Dennis@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Kim" -Surname "Dennis" -Enabled 1 -Name "Kim.Dennis" -desc "Titanium Task Force Magnetic Submarine Diver" -office "DevLabs Titanium Task Force Magnetic" -title "Submarine Diver" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass73923" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Hattie.Henry@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Hattie" -Surname "Henry" -Enabled 1 -Name "Hattie.Henry" -desc "Titanium Task Force Magnetic Paraeducator" -office "DevLabs Titanium Task Force Magnetic" -title "Paraeducator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass49354" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Katrina.Frazier@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Katrina" -Surname "Frazier" -Enabled 1 -Name "Katrina.Frazier" -desc "Titanium Task Force Magnetic Clinical Social Work Aide" -office "DevLabs Titanium Task Force Magnetic" -title "Clinical Social Work Aide" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass14909" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Christie.Hubbard@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Christie" -Surname "Hubbard" -Enabled 1 -Name "Christie.Hubbard" -desc "Uranium Squadron Grocery Stocker" -office "DevLabs Uranium Squadron" -title "Grocery Stocker" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass91353" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Johnnie.Doyle@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Johnnie" -Surname "Doyle" -Enabled 1 -Name "Johnnie.Doyle" -desc "Uranium Squadron Laryngologist" -office "DevLabs Uranium Squadron" -title "Laryngologist" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass7531" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Micheal.Mathis@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Micheal" -Surname "Mathis" -Enabled 1 -Name "Micheal.Mathis" -desc "Uranium Squadron Officer In Charge" -office "DevLabs Uranium Squadron" -title "Officer In Charge Aviation Unit Or Detachment" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass97915" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Maxine.James@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Maxine" -Surname "James" -Enabled 1 -Name "Maxine.James" -desc "Uranium Squadron Chambermaid" -office "DevLabs Uranium Squadron" -title "Chambermaid" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass28066" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Susie.Vargas@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Susie" -Surname "Vargas" -Enabled 1 -Name "Susie.Vargas" -desc "Uranium Squadron Roof Truss Builder" -office "DevLabs Uranium Squadron" -title "Roof Truss Builder" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass63429" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gayle.Mullins@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gayle" -Surname "Mullins" -Enabled 1 -Name "Gayle.Mullins" -desc "Uranium Squadron Refinery Process Engineer" -office "DevLabs Uranium Squadron" -title "Refinery Process Engineer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass65072" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Clayton.Vega@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Clayton" -Surname "Vega" -Enabled 1 -Name "Clayton.Vega" -desc "Uranium Squadron Podiatric Aide" -office "DevLabs Uranium Squadron" -title "Podiatric Aide" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass89212" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Lance.Reed@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Lance" -Surname "Reed" -Enabled 1 -Name "Lance.Reed" -desc "Uranium Squadron Certified Respiratory Therapy Technician" -office "DevLabs Uranium Squadron" -title "Certified Respiratory Therapy Technician" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass73785" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Jon.Barrett@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Jon" -Surname "Barrett" -Enabled 1 -Name "Jon.Barrett" -desc "Nano Spectral Sagittarius Ballerina" -office "DevLabs Nano Spectral Sagittarius" -title "Ballerina" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass82151" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Leigh.Bell@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Leigh" -Surname "Bell" -Enabled 1 -Name "Leigh.Bell" -desc "Nano Spectral Sagittarius Low Altitude Air Defense (Laad) Gunner" -office "DevLabs Nano Spectral Sagittarius" -title "Low Altitude Air Defense (Laad) Gunner" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass81599" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Ernestine.Carson@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Ernestine" -Surname "Carson" -Enabled 1 -Name "Ernestine.Carson" -desc "Nano Spectral Sagittarius Offset Lithographic Press Setter and Set-Up Operator" -office "DevLabs Nano Spectral Sagittarius" -title "Offset Lithographic Press Setter and Set-Up Operator" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass23341" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Martha.Maldonado@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Martha" -Surname "Maldonado" -Enabled 1 -Name "Martha.Maldonado" -desc "Nano Spectral Sagittarius Financial Director" -office "DevLabs Nano Spectral Sagittarius" -title "Financial Director" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass14969" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Calvin.Powell@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Calvin" -Surname "Powell" -Enabled 1 -Name "Calvin.Powell" -desc "Nano Spectral Sagittarius Milking Machine Mechanic" -office "DevLabs Nano Spectral Sagittarius" -title "Milking Machine Mechanic" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass34364" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Cathy.Schultz@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Cathy" -Surname "Schultz" -Enabled 1 -Name "Cathy.Schultz" -desc "Nano Spectral Sagittarius County Surveyor" -office "DevLabs Nano Spectral Sagittarius" -title "County Surveyor" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass53098" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Phyllis.Washington@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Phyllis" -Surname "Washington" -Enabled 1 -Name "Phyllis.Washington" -desc "Nano Spectral Sagittarius Oil Pipeline Dispatcher" -office "DevLabs Nano Spectral Sagittarius" -title "Oil Pipeline Dispatcher" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass75024" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Homer.Simmons@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Homer" -Surname "Simmons" -Enabled 1 -Name "Homer.Simmons" -desc "Nano Spectral Sagittarius Service Order Clerk" -office "DevLabs Nano Spectral Sagittarius" -title "Service Order Clerk" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass92861" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Delores.Wright@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Delores" -Surname "Wright" -Enabled 1 -Name "Delores.Wright" -desc "Nano Spectral Sagittarius City Alderman" -office "DevLabs Nano Spectral Sagittarius" -title "City Alderman" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass68246" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Amos.Edwards@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Amos" -Surname "Edwards" -Enabled 1 -Name "Amos.Edwards" -desc "Nano Spectral Sagittarius CEO" -office "DevLabs Nano Spectral Sagittarius" -title "CEO" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass4921" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Roy.Cross@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Roy" -Surname "Cross" -Enabled 1 -Name "Roy.Cross" -desc "Nano Spectral Sagittarius Chief Executive Officer" -office "DevLabs Nano Spectral Sagittarius" -title "Chief Executive Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass13822" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Alberta.Armstrong@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Alberta" -Surname "Armstrong" -Enabled 1 -Name "Alberta.Armstrong" -desc "Nano Spectral Sagittarius Chief Operating Officer" -office "DevLabs Nano Spectral Sagittarius" -title "Chief Operating Officer" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass78144" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Rochelle.Hughes@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Rochelle" -Surname "Hughes" -Enabled 1 -Name "Rochelle.Hughes" -desc "Nano Spectral Sagittarius Commissioner of Internal Revenue" -office "DevLabs Nano Spectral Sagittarius" -title "Commissioner of Internal Revenue" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass16043" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Irene.Houston@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Irene" -Surname "Houston" -Enabled 1 -Name "Irene.Houston" -desc "Nano Spectral Sagittarius COO" -office "DevLabs Nano Spectral Sagittarius" -title "COO" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass51156" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Byron.Lawrence@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Byron" -Surname "Lawrence" -Enabled 1 -Name "Byron.Lawrence" -desc "Nano Spectral Sagittarius County Commissioner" -office "DevLabs Nano Spectral Sagittarius" -title "County Commissioner" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass74862" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Marion.Gonzalez@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Marion" -Surname "Gonzalez" -Enabled 1 -Name "Marion.Gonzalez" -desc "Nano Spectral Sagittarius Government Service Executive" -office "DevLabs Nano Spectral Sagittarius" -title "Government Service Executive" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass62004" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Gerald.Wade@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Gerald" -Surname "Wade" -Enabled 1 -Name "Gerald.Wade" -desc "Nano Spectral Sagittarius City Alderman" -office "DevLabs Nano Spectral Sagittarius" -title "City Alderman" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass35101" -AsPlainText -Force) -Credential $Cred
New-ADUser -UserPrincipalName  Donna.Garner@labs.local -Path "ou=UserAccounts,dc=labs,DC=local" -Server labs.local -GivenName "Donna" -Surname "Garner" -Enabled 1 -Name "Donna.Garner" -desc "Compu Matrix M City Council Member" -office "DevLabs Compu Matrix M" -title "City Council Member" -company "DevLabs" -AccountPassword (ConvertTo-SecureString "Badpass63050" -AsPlainText -Force) -Credential $Cred
Add-ADGroupMember -Identity "Domain Admins" -Members Sylvia.Sutton -Server labs.local -Credential $Cred
Move-ADObject -Identity "CN=$user,CN=Users,DC=labs,DC=local" -TargetPath "OU=AdminAccounts,DC=labs,DC=local" -Server labs.local -Credential $Cred
Move-ADObject -Identity "CN=ws01,CN=Computers,DC=labs,DC=local" -TargetPath "OU=ComputerAccounts,DC=labs,DC=local" -Server labs.local -Credential $Cred
Set-ADUser $user -ScriptPath �\\dc01.labs.local\labs\scripts\mapdrive.bat -Server labs.local -Credential $Cred
