# code: language=ansible

---
- hosts: localhost
  connection: local
  become: false
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  vars:
    os_environment:
      - key: EDITOR
        value: vim
  pre_tasks:
    - name: Print network interface info
      ansible.builtin.debug:
        msg: |
          # get public ip address
          curl icanhazip.com

          # get active network interface
          ip link show

          # get private ip address
          ip addr show enp0s1 | grep -Po 'inet \K[\d.]+'

    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"
        work_dir: "{{ playbook_dir | dirname }}"
        cacheable: true

    - name: Top-level directory in project
      ansible.builtin.command: git rev-parse --show-toplevel
      register: tld

    - name: Enable ssh
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true

    - name: Add deadsnakes ppa
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: true
      become: true

    - name: Install pip
      become: true
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Cross-platform dependencies
      ansible.builtin.package:
        name:
        - ansible
        - ansible-lint
        - ca-certificates
        - cloud-init
        - git
        - inxi
        - p7zip-full
        - python3.11
        - python3.11-venv
        - tldr
        - tree
        - vim
        - wget
        state: present
      become: true

    - name: Create default directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ home_dir }}/git"
        - "{{ home_dir }}/Desktop"
        - "{{ home_dir }}/Documents"
        - "{{ home_dir }}/Downloads"
        - "{{ home_dir }}/Music"
        - "{{ home_dir }}/Pictures"
        - "{{ home_dir }}/Public"
        - "{{ home_dir }}/Templates"
        - "{{ home_dir }}/Videos"

  tasks:
    - name: Set /opt permissions
      ansible.builtin.file:
        path: /opt
        mode: '0777'
        state: directory
      become: true

    - name: Download linuxtools.7z
      ansible.builtin.get_url:
        url: https://github.com/pythoninthegrass/apt_lab_tf_linux/raw/master/linuxtools.7z
        dest: /opt/linuxtools.7z

    - name: Extract linuxtools.7z
      ansible.builtin.command: |
        7z x -y /opt/linuxtools.7z

    - name: Create tools directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/SilentTrinity
        - /opt/CrackMapExec

    - name: Move silenttrinity
      ansible.builtin.command: |
        mv /opt/st /opt/SilentTrinity/

    - name: Move crackmapexec
      ansible.builtin.shell: |
        mv /opt/cme* /opt/CrackMapExec/

    - name: Remove linuxtools.7z
      ansible.builtin.file:
        path: /opt/linuxtools.7z
        state: absent

    - name: Clone responder
      ansible.builtin.git:
        repo: https://github.com/lgandx/Responder.git
        dest: /opt/Responder

    - name: Clone impacket
      ansible.builtin.git:
        repo: https://github.com/SecureAuthCorp/impacket.git
        dest: /opt/impacket

    - name: Setup python virtual environment for impacket
      ansible.builtin.command: python3.11 -m venv /opt/impacket/env

    - name: Clone helk
      ansible.builtin.git:
        repo: https://github.com/Cyb3rWard0g/HELK.git
        dest: /opt/helk

    # TODO: run on x86_64 vm
    - name: Run helk docker container
      ansible.builtin.shell: |
        /opt/helk/docker/helk_install.sh -p hunting -i 10.10.98.20 -b 'helk-kibana-analysis-alert'
      become: true
      tags: qa
